### ISSUE TITLE
Add option to use theme color as background

### ISSUE THREAD

**Issue by glenswift** [tonai/storybook-addon-themes#1]
My dark theme is barely visible on default background so I'd like to have possibility to use theme's color as background (similar to the way @storybook/addon-backgrounds works).

What do you think about it? I can create pull request

**Comment by tonai** [comment]
Hi @glenswift 
I don't really understand you want.

You can use this plugin to add a class on the root element, and then with CSS you use that class to set the background you want (or any CSS properties).

**Comment by glenswift** [comment]
That makes perfect sense, thanks. I was confused at the beginning since we're using root CSS classes  to support multiple themes i.e:

```css
.theme-light {
  --primary-color: white
  /* other variables */
}

.theme-dark {
  --primary-color: black
  /* other variables */
}
```

This classes doesn't have any backgrounds or something, only variable declarations. Anyway, I've created separate css for storybook and just injected both classes (`.theme-light` and `.storybook-theme-light`) and it works like a charm
